import json
from datetime import datetime
from pathlib import Path

import streamlit as st

import ai
import db

conn = st.connection("game", type="sql")

st.set_page_config("Humans vs. Machines", page_icon=":material/smart_toy:")
st.html(Path("static/style.css"))

if "ai" not in st.session_state:
    st.switch_page("main.py")

using_ai = st.session_state.ai


# This is FAKE data generated by copilot
@st.cache_data
def get_round_data():
    with open("static/fake_medical_notes.json") as data:
        return json.load(data)


def check_answer(response: str, answer: str) -> bool:
    return (
        response.strip().split(" ")[0].lower() == answer.strip().split(" ")[0].lower()
    )


def next_round():
    # Advance to the next round
    st.session_state.round += 1

    # Clear chat history
    if "messages" in st.session_state:
        st.session_state.messages.clear()


if using_ai:
    st.markdown("# :material/smart_toy: Human + AI")
else:
    st.markdown("# :material/face: Human")

if "round" not in st.session_state:
    st.session_state.round = 1

current_round = st.session_state.round
round_data = get_round_data()
num_rounds = len(round_data)

if current_round > num_rounds:
    st.success("Completed!")
    st.stop()

st.progress(
    current_round / num_rounds, text=f"**QUESTION {current_round}/{num_rounds}**"
)


round_info = round_data[current_round - 1]
note = round_info["note"]
question = round_info["question"]
answer = round_info["answer"]

session_key_round_start = f"{current_round}_start"
session_key_round_end = f"{current_round}_end"
session_key_round_incorrect = f"{current_round}_incorrect"
if session_key_round_incorrect not in st.session_state:
    st.session_state[session_key_round_incorrect] = 0

st.markdown("#### :material/notes: Notes")
show_note_clicked = False
round_started = session_key_round_start in st.session_state

if not round_started:
    show_note_clicked = st.button(
        "Show notes",
        key="show_note",
        type="primary",
        icon=":material/timer_play:",
        use_container_width=True,
    )
    if show_note_clicked:
        st.session_state[session_key_round_start] = datetime.now()
        st.rerun()
else:
    for note_part in note.split("\n"):
        st.html(f"<p class='note'>{note_part}</p>")

st.write("#### :material/quiz: Question")
st.html(f"<p class='question'>{question}</p>")

if session_key_round_end not in st.session_state:
    if round_started:
        with st.form("input"):
            response = st.text_input(":material/edit_document: Response")
            waiting_for_assistant = using_ai and not len(st.session_state.messages)
            submit = st.form_submit_button(
                "Submit",
                type="primary",
                use_container_width=True,
                disabled=waiting_for_assistant,
            )
            if submit and response != "":
                if check_answer(response, answer):
                    end_time = datetime.now()
                    st.session_state[session_key_round_end] = end_time
                    start_time = st.session_state[session_key_round_start]
                    guesses = st.session_state[session_key_round_incorrect] + 1
                    db.add_result(
                        conn, current_round, start_time, end_time, guesses, using_ai
                    )
                    st.rerun()
                else:
                    st.error("Incorrect - try again!", icon=":material/error:")
                    st.session_state[session_key_round_incorrect] += 1
else:
    time_elapsed = (
        st.session_state[session_key_round_end]
        - st.session_state[session_key_round_start]
    )
    elapsed_seconds = time_elapsed.total_seconds()
    incorrect_guesses = st.session_state[session_key_round_incorrect]
    total_guesses = incorrect_guesses + 1

    st.success(
        f"Correct - completed in {elapsed_seconds}s with {total_guesses} guess{'es' if total_guesses > 1 else ''}",
        icon=":material/check_circle:",
    )
    st.balloons()

    st.button(
        "Next",
        on_click=next_round,
        type="primary",
        icon=":material/arrow_circle_right:",
        use_container_width=True,
    )

if using_ai:
    with st.sidebar:
        ai.render_assistant(round_started, note, question)
